### PR TITLE
[FIXES JENKINS-27136] Workflow plugin support

### PR DESCRIPTION
**Pull request by lanwen**
Superseed of #59 (squashed and rebased)

[Review on Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/82)

### CODE REVIEW

**Comment by lanwen** [comment]
@amuniz Please review squashed and rebased version with some additional changes

**Comment by amuniz** [comment]
Code looks good. Thanks for the additional tests.
Some smoke testing done, everything is working as expected.

**Comment by austinnichols101** [comment]
@amuniz where can I find documentation on how to enable this in my workflow?

**Comment by KostyaSha** [comment]
@austinnichols101 please read appropriate documentation about workflow-plugin.

**Comment by lanwen** [comment]
its not released at this moment, we plan to do it soon

**Comment by amuniz** [comment]
@austinnichols101 once it it is released, you'll see the Github trigger checkbox available in any workflow job configuration page. You just would need to check it.

**Comment by lanwen** [comment]
@KostyaSha can you link them? 2.3.5 have issues too, so there is no stable version at all?

**Comment by KostyaSha** [comment]
i can't debug this issue, i tried different plugin versions and git clients. I will inform you directly. 
Hope @MarkEWaite will do some magic release that will magically solve issues.... And it will allow us to have more than one version in dependency range.

**Comment by amuniz** [comment]
As far as I remember, it was on 2.3.5 in the original PR.

**Comment by lanwen** [comment]
@amuniz yep,
but 2.4.0 contains:
>Display error message in log when fetch fails (regression fix) (issue #26225, issue #27567, issue #27886, issue #28134)
   Fix IllegalStateException when using notifyCommit URL (issue #26582)
   Allow branch specification regex which does not include '*' (issue #26842)
   Detect changes correctly when polling (issue #27093, issue #27332, issue #27769)
   Fix GitHub Webhook handling (issue #27282)
   Fix polling with a parameterized branch name (issue #27349)
   Don't throw exception when changelog entry is missing parent (issue #28260, issue #28290, issue #28291)
   Don't throw exception when saving GitLab browser config (issue #28792)
   Rebuild happened on each poll, even with no changes (issue #29066)
   Remote class loading issue work-around (issue #21520)

@KostyaSha maybe release it as alpha version? I've already use 2.4.0 git on all my instances and it works fine...

**Comment by KostyaSha** [comment]
> Detect changes correctly when polling (issue #27093, issue #27332, issue #27769)

lol

> Allow branch specification regex which does not include '*' (issue #26842)

Probably caused part of issues and broken logic

> Rebuild happened on each poll, even with no changes (issue #29066)

Seems fixed his case and broke other.

Alpha is ok.

**Comment by lanwen** [comment]
can be installed from [Experimental Update Center](http://jenkins-ci.org/content/experimental-plugins-update-center) as 1.14.0-alpha-1

**Pull request merged**
