### PR TITLE
Always update existing hooks to make sure all options (e.g. shared se…

### PR DESCRIPTION
**Pull request by silbernm**
…cret) are up-to-date

Easy option for solving https://issues.jenkins-ci.org/browse/JENKINS-48610.

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/185)

### CODE REVIEW

**Comment by KostyaSha** [comment]
Looks like a hack, is there any more strict way to verify that secret changed?

**Comment by silbernm** [comment]
I don't think there is a reliable way to detect secret changes. Unfortunately, GitHub returns the value "********" for the secret of an existing hook.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/github-plugin/185#-:-L2RXbRrDVfxt6eLWsV5:b-1cm0hb)*

**Comment by KostyaSha** [comment]
So if secret exists and configured we should update it?

**Comment by silbernm** [comment]
True, we don't have to update the hook if no secret is configured in the github plugin. In that case, we can also leave an already configured secret in the hook, since the github plugin just discards the X-Hub-Signature.

As described in the the accompanying bug https://issues.jenkins-ci.org/browse/JENKINS-48610, we could also just update the secret value of the hook. This however would require quite some changes to the GitHub API plugin, and still result in the same number of HTTP requests.

I was also thinking of just updating a hook if we receive a hook payload with an invalid X-Hub-Signature. However, an attacker could then trick us into flooding GitHub with hook update requests.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/github-plugin/185#-:-L2R_z50UzpigHyr8Cam:b-eb32ba)*

**Comment by silbernm** [comment]
To answer your questions more directly: Yes, if the secret is configured in the GitHub plugin, we must update the hook, because we can't check whether the secret in the hook is correct.

Since we read the secret from the Jenkins credentials, we can't know when the secret has been changed for the last time. For example, a user could modify the credential files on the disk without us knowing. And even if we were able to detect both the last change of the secret in Jenkins and in GitHub, I think it would be too fragile to just assume that the secret is correct if the change in GitHub was later than the change in Jenkins.

A completely different solution that comes to my mind is the following: We could add an optional parameter to the GitHubPluginConfig.doReRegister method and a "Force" checkbox right next to the "Re-register hooks for all jobs" button in the GitHub plugin configuration. Then we could keep the current behavior by default, but let the user regenerate all hooks unconditionally if desired.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/github-plugin/185#-:-L2RoAVfZmEaixtZAFSP:b-6ma96g)*

**Comment by lanwen** [comment]
will it really replace the hook? Or just add new?

**Comment by silbernm** [comment]
@lanwen: I have not touched the code that updates an existing hook. But yes, I have tested the patched plugin, and it replaces any existing hooks.

@KostyaSha: I have pushed changes such that the hooks are only replaced unconditionally if the secret is not configured in the GitHub plugin.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/github-plugin/185#-:-L2S-WvTbEC15kKXbYrB:bfpibsr)*

**Comment by ljupchokotev** [comment]
Is there anything blocking this from being merged? It is really useful if you have a lot of repositories and you need to update the shared secret for the webhook. Currently, it means going and manually changing it in each repository webhook configuration or deleting the webhook from all repositories and let Jenkins re-register it. It is a lot of manual work either way.

**Comment by KostyaSha** [comment]
> However, an attacker could then trick us into flooding GitHub with hook update requests.

Probably he can do it with re-registration also. As soon as job will be reconfigured jenkins will attempt to set token...
We can add global option with default new behavior and delete it after few releases.

**Comment by silbernm** [comment]
@KostyaSha: Reconfiguring a job requires the attacker to be logged into Jenkins. The attack with the invalid X-Hub-Signature could be performed without login. Therefore, I would still prefer the PR as implemented right now: If a job has a secret, then its webhook gets re-registered in GitHub even if it already exists.

This PR is now over a year old - is anybody still interested in this contribution? If so, I am happy to tackle any specific remarks. If not, I'm going to close it end of February.

**Comment by ljupchokotev** [comment]
I am still interested in this. I believe this PR makes more sense than the current logic for the webhooks.

**Pull request closed without merging**
