### PR TITLE
Correcting @Symbol dependency

### PR DESCRIPTION
**Pull request by jglick**
#166 was incorrect.

@reviewbybees

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/176)

### CODE REVIEW

**Comment by KostyaSha** [comment]
@jglick where is documentation for this things?

**Comment by KostyaSha** [comment]
PR failed?

**Comment by jglick** [comment]
> where is documentation for this things?

A work in progress.

**Comment by jglick** [comment]
Anyway you need do nothing special if you have a 2.x baseline, which at this point is pretty uncontroversial.

**Pull request merged**
