### PR TITLE
[FIXES JENKINS-32132] Check status message is null (in case of wrong …

### PR DESCRIPTION
**Pull request by lanwen**
…deserialization)

[Review on Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/103)

### CODE REVIEW

**Comment by lanwen** [comment]
test will be in next pr

**Comment by KostyaSha** [comment]
If you are making this property ready for null, then mark it with `@CheckForNull` but i would prefer to see `readResolve()` and `@Nonnull` field or getter.

**Comment by KostyaSha** [comment]
> test will be in next pr

Sorry where is it?

**Comment by lanwen** [comment]
this is a hotfix, so implementation may change after test will be ready (im working on gh mock)

**Pull request merged**
