### PR TITLE
Avoid com.thoughtworks.xstream.annotations

### PR DESCRIPTION
**Pull request by jglick**
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.

### CODE REVIEW

**Comment by jglick** [comment]
CheckStyle quality gate also broken in trunk.

**Comment by jglick** [comment]
I believe this is safe to merge & release now, yes.

**Comment by MRamonLeon** [comment]
@lanwen @integer @oleg-nenashev Could you release this changes? Thank you.

**Comment by jglick** [comment]
@KostyaSha ping

**Comment by KostyaSha** [comment]
@jglick i wanted to merge PR but didn't get PR builds working. Need verify build locally and then can release.

**Comment by KostyaSha** [comment]
@jglick please check 1.32.0

**Pull request merged**
