### PR TITLE
[FIXED JENKINS-36446] Ensure all plugin extensions are initialized before migration

### PR DESCRIPTION
**Pull request by stephenc**
See [JENKINS-36446](https://issues.jenkins-ci.org/browse/JENKINS-36446)

@reviewbybees

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/150)

### CODE REVIEW

**Comment by stephenc** [comment]
Unsure what is up with Travis and its test failure... Jenkins had no issue building

**Comment by KostyaSha** [comment]
Travis is known issue, i see no exact version from reporter and initializers was adjusted in last release. Did you reproduce and fix issues locally or blindly adopted initializers as you feeling?

**Comment by stephenc** [comment]
@KostyaSha it is incorrect to run code that invokes other plugins prior to `EXTENSIONS_AUGMENTED` as that is the first stage in the lifecycle where the `ExtensionList` is committed. So doesn't matter that you refactored the code, the migration wants to migrate credentials, therefore it needs to invoke the credentials plugin, therefore the migration *must* be at least after `EXTENSIONS_AUGMENTED` or the Jenkins master will fail to start

**Comment by KostyaSha** [comment]
@stephenc ok, could you create some test with TestPluginExtension that will show behaviour?

**Comment by rsandell** [comment]
:bee:

**Comment by stephenc** [comment]
@KostyaSha I do not have time to work on this issue further. It is not infinite fixing BTW, it is the complete inability to have fixing work. To reproduce I suspect all you need to do is start with an old version of the plugin with some legacy credentials defined, then upgrade this plugin and credentials plugin at the same time... restart... boom!

**Comment by KostyaSha** [comment]
Would be greate to block this PR until you fix https://github.com/jenkinsci/workflow-job-plugin/pull/28 , but because of users of course it will be solved 10x time faster then you handle community.

**Comment by KostyaSha** [comment]
cc @lanwen

**Comment by stephenc** [comment]
@kostyasha I cannot be everywhere all at once... ;-)

**Comment by stephenc** [comment]
Thanks @lanwen

**Pull request merged**
