### PR TITLE
Add Chinese translation

### PR DESCRIPTION
**Pull request by LinuxSuRen**
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/193)

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
@jenkinsci/code-reviewers Anyone could help me to review this PR?

**Comment by oleg-nenashev** [comment]
@KostyaSha @lanwen PTAL

**Comment by KostyaSha** [comment]
Do we have somebody else from china to review changes?

**Comment by daniel-beck** [comment]
@KostyaSha Not sure we have active contributors, but @LinuxSuRen is a long-time contributor of translations, and previously spot-checked [PRs from core](https://github.com/jenkinsci/jenkins/pulls?q=is%3Apr+author%3Alinuxsuren+is%3Aclosed) always looked good.

**Comment by LinuxSuRen** [comment]
Thanks to everyone, github-plugin is very popular, so I will keep in focus.

**Pull request merged**
