### PR TITLE
[JENKINS-33974] Payload verification using shared secrets

### PR DESCRIPTION
**Pull request by lanwen**
Closes #129

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/134)

### CODE REVIEW

**Comment by MartinNowak** [comment]
This seems to fail for some form encoded payloads, like the one attached below @lanwen.
[payload.encoded.txt](https://github.com/jenkinsci/github-plugin/files/818832/payload.encoded.txt)
[payload.json.txt](https://github.com/jenkinsci/github-plugin/files/818833/payload.json.txt)

Running `URLEncode(URLDecode(payload))` does not return the same result, apparently b/c `~` is encoded by Java but not by GH.

**Comment by lanwen** [comment]
@MartinNowak can you write a test to reproduce? (And may be a full fix?:)

**Comment by MartinNowak** [comment]
No, too much time already spent on figuring this out, and I'm neither familiar with nor keen to dig further into this mass of Java code/plugins.
The obvious fix is to checksum the original request body instead of trying to recreate it from the decoded form.

There isn't much wrong with recommending application/json as workaround, though GH uses application/x-www-form-urlencoded by default which applies to the hooks installed by github-organization (or github-branch-source or github-api or whatever).

**Comment by lanwen** [comment]
Ok, thanks in any case, will try to do something

**Comment by nh2** [comment]
I'm also still seeing `Provided signature [aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa] did not match to calculated` for specific branch names, when using `application/x-www-form-urlencoded`.

I suspect in my case it's because the branch name contains a `.`

**Pull request merged**
