### PR TITLE
WIP [JENKINS-33228] Consolidation of the GitHub Server list

### PR DESCRIPTION
**Pull request by stephenc**
Todo

- [x] Refactor credentials usage to use authentication tokens
- [ ] Migrate existing credentials to GitHub OAuth credential type
- [ ] Change server configuration to enable extension by other plugins that need to record information

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/181)

### CODE REVIEW

**Comment by stephenc** [comment]
@lanwen could you add a Work In Progress label to this PR please?

**Comment by KostyaSha** [comment]
> Migrate existing credentials to GitHub OAuth credential type

Reason?

**Comment by stephenc** [comment]
Because they should not be SecretText. They are specific to connecting to GitHub. The use of SecretText is against the design principles of the credentials API. Additionally it does not allow for filtering based on permissions granted to the credentials. 

Should be transparent when I get it implemented

**Comment by KostyaSha** [comment]
> I. Additionally it does not allow for filtering based on permissions granted to the credentials.

https://github.com/KostyaSha/github-integration-plugin/blob/master/github-pullrequest-plugin/src/main/java/com/github/kostyasha/github/integration/generic/repoprovider/GitHubPluginRepoProvider.java#L32

Exists for one year. You still reinventing bicycle with github features. Plus we have fully working and integrated with oauth instance based on github-integration-plugin . 

> The use of SecretText is against the design principles of the credentials API.

DomainRequirements?

**Comment by stephenc** [comment]
1. Did you even look at the linked PR, which is mapping EndPoint to the global config in this plugin. 

2. Domain requirements are for a different set of use cases

Seriously, just wait and see what I have planned, I discussed all this with @lanwen previously and told me he agreed with the plan I have.

**Comment by stephenc** [comment]
tumbleweed

**Pull request closed without merging**
