### PR TITLE
[JENKINS-43786] Adapted the administrative monitor to the new UI definition

### PR DESCRIPTION
**Pull request by recena**
[JENKINS-43786](https://issues.jenkins-ci.org/browse/JENKINS-43786)

Downstream of https://github.com/jenkinsci/jenkins/pull/2857

### Screenshot

screenshot-2017-9-14 manage jenkins jenkins 1

@jenkinsci/code-reviewers

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/177)

### CODE REVIEW

**Comment by recena** [comment]
@lanwen Thanks for your feedback. This PR has a drawback, it will require to bump the core version to the version where this PR https://github.com/jenkinsci/jenkins/pull/2857 is merged.

**Comment by lanwen** [comment]
@recena this is too huge change for this plugin...

**Comment by KostyaSha** [comment]
> @lanwen Thanks for your feedback. This PR has a drawback, it will require to bump the core version to the version where this PR jenkinsci/jenkins#2857 is merged.

Bad.

**Comment by recena** [comment]
@lanwen Agree. You can apply these changes in midterm. This depends on changes in Jenkins. What I would like is to get those changes in core as soon as possible, and in this way, maintainers could adapt their plugins when they decide.

**Comment by recena** [comment]
@KostyaSha Again I agree. I tried to share the pros / cons.

**Comment by lanwen** [comment]
How would it look if I merge it now?

**Comment by lanwen** [comment]
So it just changes the position of text in old versions
image

**Comment by recena** [comment]
@lanwen I've worked on a more robust solution. You can see an example here https://github.com/jenkinsci/ssh-slaves-plugin/pull/70. Maintainers will be able to use the benefits of https://github.com/jenkinsci/jenkins/pull/2857 without side-effects in previous versions.

You screenshot is showing a side-effect until the baseline of this plugin is updated.

**Pull request merged**
