### PR TITLE
JENKINS-66317 Forwards compatible for guava upgrade

### PR DESCRIPTION
**Pull request by timja**
https://issues.jenkins.io/browse/JENKINS-66317

cc @oleg-nenashev @KostyaSha

### CODE REVIEW

**Review by KostyaSha — APPROVED** [review]
lgtm

**Comment by KostyaSha** [comment]
jira issue mention also `Hasher#putString` should it be also fixed?

**Comment by timja** [comment]
> jira issue mention `Hasher#putString` should it be also fixed?

That's fixed in src/main/java/org/jenkinsci/plugins/github/internal/GitHubClientCacheOps.java

By specifying the charset

**Review by oleg-nenashev — APPROVED** [review]
🚢 🇮🇹

**Comment by timja** [comment]
🚢  ?

**Comment by timja** [comment]
Would it be possible to do a release please?

**Pull request merged**
