### PR TITLE
Add CI service from ci.jenkins.io

### PR DESCRIPTION
**Pull request by stephenc**
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/174)

### CODE REVIEW

**Comment by stephenc** [comment]
@lanwen @KostyaSha looks like some interesting failures on Windows will be exposed with this one

**Comment by lanwen** [comment]
Seems `GitHubClientCacheCleanupTest` works only on nix

**Comment by KostyaSha** [comment]
What i see on this ugly UI is that windows and linux has red icons, so both failed

**Comment by lanwen** [comment]
will fix that later...

**Comment by stephenc** [comment]
@KostyaSha the linux build was interrupted by the failure in the windows build

**Comment by KostyaSha** [comment]
@stephenc stupid logic, CI should show the real result

**Comment by stephenc** [comment]
@KostyaSha take it up with @rtyler or whoever wrote the shared library such that a failure on one of linux/windows triggers an abort of the other

**Comment by lanwen** [comment]
It looks like linux build time outed

**Pull request merged**
