### PR TITLE
Pick maven-hpi-plugin 120 with coordinated run

### PR DESCRIPTION
**Pull request by KostyaSha**
testing possible regressions with missing .js

---

This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/github-plugin/143)

### CODE REVIEW

**Comment by lanwen** [comment]
Will be any more work here?

**Comment by KostyaSha** [comment]
If you approve - merge it

**Comment by lanwen** [comment]
can u rebase it to simplify review? I want take a look on it once more

**Comment by KostyaSha** [comment]
Shit happened after my yesterday failure :(

**Pull request closed without merging**
