### PR TITLE
Require Jenkins 2.479.1 LTS or newer

### PR DESCRIPTION
**Pull request by basil**
Completes the migration started in #380 by moving from EE 8 to EE 9 and `javax` to `jakarta` imports.

### Testing done

Ran `mvn clean verify` on Java 21 locally.

### CODE REVIEW

**Comment by basil** [comment]
Thanks @KostyaSha! 2.479.3 LTS is about to phase out into 2.492.1, so now is a good time for this to be released if you are interested in performing a release.

**Comment by KostyaSha** [comment]
```
INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unknown packaging: hpi @ com.coravy.hudson.plugins.github:github:${revision}${changelist}, /Users/integer/src/github/github-plugin-release/pom.xml, line 15, column 16
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.coravy.hudson.plugins.github:github:1.40.1-SNAPSHOT (/Users/integer/src/github/github-plugin-release/pom.xml) has 1 error
[ERROR]     Unknown packaging: hpi @ com.coravy.hudson.plugins.github:github:${revision}${changelist}, /Users/integer/src/github/github-plugin-release/pom.xml, line 15, column 16
[
```

**Comment by basil** [comment]
A product of using old Maven/Java versions. Maven 3.9.9 and Java 17 should work just fine.

**Comment by KostyaSha** [comment]
done

**Pull request merged**
